### PR TITLE
Additional API changes for parameters to the CKKS encoding functions

### PR DESCRIPTION
**Pull request by faberga**
Raising this PR on behalf of Victor:

The two optional parameters are now:

double mag, long prec;

The semantics are now as follows:

// mag: defaults to Norm(array).
// prec: defaults to r=getAlMod().getR(), which
// is usually the same as context.getDefaultPrecision().

// mag should be an upper bound on Norm(array).
// If an encoding will be encrypted, the user may wish
// to hide Norm(array) by setting mag to some data-independent
// upper bound. A warning is issued if Norm(array) > mag.

// The encoding will normally have an accuracy of 2^{-prec}, meaning that
// Norm(array - decode(encode(array))) <= 2^{-prec}.
// Note that prec may be positive, negative, or zero.
// The exact logic is a bit heuristic, and a warning is
// issued if the the accuracy exceeds 2^{-prec}.

// NOTE: Norm above is the infinity (i.e., max) norm.

### CODE REVIEW

**Comment by faberga** [comment]
Jenkins run tests

**Comment by victorshoup** [comment]
Just checking: the ckks_mitigation branch forked off of the last_minute_api_tweaks
branch.  I assume (hope) you're merging the mitigations branch.

**Comment by faberga** [comment]
@victorshoup 
I noticed that when I found `last_minute_api_tweaks` PR in homenc too.

we are going to do the merges in the right order:
1- `last_minutes_api_tweaks`
2- `CKKS mitigation`
This way, the mitigation will be self contained in its own PR

**Comment by faberga** [comment]
Jenkins run tests

**Review by esteffin — APPROVED** [review]
Looks good to me

**Comment by faberga** [comment]
Passed Build & Tests in Travis and full Jenkins pipeline

**Pull request merged**
