### PR TITLE
Multiplication test fixes

### PR DESCRIPTION
**Pull request by jlhcrawford**
- Added extra checks for relinearisation after certain multiplications.
- Added in test for `ctxt.square()`.
- Added in check for `operator*=` on `Ctxt`.
- Introduced `TestBGV` which performs similar tests as in `TestCKKS`.

### CODE REVIEW

**Comment by esteffin** [comment]
Jenkins run tests no benchmarks

**Comment by faberga** [comment]
Jenkins run tests

**Comment by faberga** [comment]
Jenkins run tests

**Review by faberga — APPROVED** [review]
Passed all tests

**Pull request merged**
